using System;
using System.Collections.Generic;

namespace Core.Entity.BizModels
{
    public partial class EmployeePerformanceReportFinal
    {
        public long Id { get; set; }
        public DateTime StatDate { get; set; }
        public string RegionCode { get; set; }
        public string RegionName { get; set; }
        public int? EmployeeId { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public Guid? JobId { get; set; }
        public string JobName { get; set; }
        public DateTime? EntryDate { get; set; }
        public string DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
        public string DeptEmployeeCode { get; set; }
        public string DeptEmployeeName { get; set; }
        public string BigRegionCode { get; set; }
        public string BigRegionName { get; set; }
        public string RegionEmployeeCode { get; set; }
        public string RegionEmployeeName { get; set; }
        public string AreaCode { get; set; }
        public string AreaName { get; set; }
        public string AreaEmployeeCode { get; set; }
        public string AreEmployeeName { get; set; }
        public int? TeamId { get; set; }
        public string TeamCode { get; set; }
        public string TeamName { get; set; }
        public string TeamEmployeeCode { get; set; }
        public string TeamEmployeeName { get; set; }
        public int? AddRealtyRent { get; set; }
        public int? AddRealtyfirstRent { get; set; }
        public int? AddRealtysecondRent { get; set; }
        public int? AddRealtyotherRent { get; set; }
        public int? AddRealtySale { get; set; }
        public int? AddRealtyfirstSale { get; set; }
        public int? AddRealtysecondSale { get; set; }
        public int? AddRealtyotherSale { get; set; }
        public int? AddRealtyRentsale { get; set; }
        public int? AddRealtyfirstRentsale { get; set; }
        public int? AddRealtysecondRentsale { get; set; }
        public int? AddRealtyotherRentsale { get; set; }
        public int? AddRealtySum { get; set; }
        public int? KeyRealtySum { get; set; }
        public int? SoleAgentOrdinary { get; set; }
        public int? SoleAgentTime { get; set; }
        public int? SoleAgentRent { get; set; }
        public int? AddCustomerRent { get; set; }
        public int? AddCustomerfirstRent { get; set; }
        public int? AddCustomersecondRent { get; set; }
        public int? AddCustomerotherRent { get; set; }
        public int? AddCustomerSale { get; set; }
        public int? AddCustomerfirstSale { get; set; }
        public int? AddCustomersecondSale { get; set; }
        public int? AddCustomerotherSale { get; set; }
        public int? AddCustomerSum { get; set; }
        public int? FollowupRealty { get; set; }
        public int? FollowupCustomer { get; set; }
        public int? FollowupSum { get; set; }
        public int? EncounterRent { get; set; }
        public int? EncounterSaleFirst { get; set; }
        public int? EncounterSaleSecond { get; set; }
        public int? EncounterMix { get; set; }
        public decimal? DepositNumRent { get; set; }
        public decimal? DepositNumRentagent { get; set; }
        public decimal? DepositNumFirstLx { get; set; }
        public decimal? DepositNumFirstnoneLx { get; set; }
        public decimal? DepositNumSecond { get; set; }
        public decimal? DepositNumOther { get; set; }
        public decimal? DepositMoneyRent { get; set; }
        public decimal? DepositMoneyRentagent { get; set; }
        public decimal? DepositMoneyFirstLx { get; set; }
        public decimal? DepositMoneyFirstnoneLx { get; set; }
        public decimal? DepositMoneySecond { get; set; }
        public decimal? DepositMoneyOther { get; set; }
        public decimal? TransactionNumFirstLx { get; set; }
        public decimal? TransactionNumFirstnoneLx { get; set; }
        public decimal? TransactionNumSecond { get; set; }
        public decimal? TransactionNumRent { get; set; }
        public decimal? TransactionNumRentagent { get; set; }
        public decimal? TransactionNumOther { get; set; }
        public decimal? AchievementFirstLx { get; set; }
        public decimal? AchievementFirstnoneLx { get; set; }
        public decimal? AchievementSecond { get; set; }
        public decimal? AchievementRent { get; set; }
        public decimal? AchievementRentZz { get; set; }
        public decimal? AchievementRentZh { get; set; }
        public decimal? AchievementRentCf { get; set; }
        public decimal? AchievementOther { get; set; }
        public bool? IsCount { get; set; }
        public DateTime? CreateTime { get; set; }
        public int? EmpFlag { get; set; }
        public byte[] UpdateFlag { get; set; }
        public string HashCode { get; set; }
        public int? UpimageSale { get; set; }
        public int? UpimageRent { get; set; }
        public int? UpimageRentsale { get; set; }
        public int? UpimageSum { get; set; }
        public int? AddCus1r { get; set; }
        public int? AddCusone1r { get; set; }
        public int? AddCustwo1r { get; set; }
        public int? AddCusoth1r { get; set; }
        public int? AddCus2r { get; set; }
        public int? AddCusone2r { get; set; }
        public int? AddCustwo2r { get; set; }
        public int? AddCusoth2r { get; set; }
        public int? AddCus12r { get; set; }
        public int? AddCusone12r { get; set; }
        public int? AddCustwo12r { get; set; }
        public int? AddCusoth12r { get; set; }
        public int? AddCus1s { get; set; }
        public int? AddCusone1s { get; set; }
        public int? AddCustwo1s { get; set; }
        public int? AddCusoth1s { get; set; }
        public int? AddCus2s { get; set; }
        public int? AddCusone2s { get; set; }
        public int? AddCustwo2s { get; set; }
        public int? AddCusoth2s { get; set; }
        public int? AddCus12s { get; set; }
        public int? AddCusone12s { get; set; }
        public int? AddCustwo12s { get; set; }
        public int? AddCusoth12s { get; set; }
    }
}
