using System;
using System.Collections.Generic;

namespace Core.Entity.BizModels
{
    public partial class Realty
    {
        public int RealtyId { get; set; }
        public Guid? RealtyGuid { get; set; }
        public int? DistrictId { get; set; }
        public string DistrictName { get; set; }
        public int? CommunityIndexId { get; set; }
        public string CommunityIndexName { get; set; }
        public int? CommunityId { get; set; }
        public string CommunityName { get; set; }
        public string CommunityAlias { get; set; }
        public int? BuildingId { get; set; }
        public string BuildingName { get; set; }
        public int? RoomId { get; set; }
        public string RoomName { get; set; }
        public int? FloorNum { get; set; }
        public string FloorName { get; set; }
        public int? FloorsTotal { get; set; }
        public string RealtyNum { get; set; }
        public string Stations { get; set; }
        public int? SourceType { get; set; }
        public int? TradeStatus { get; set; }
        public int? PropertyType { get; set; }
        public DateTime? PropertyStartDate { get; set; }
        public DateTime? PropertyEndDate { get; set; }
        public string Address { get; set; }
        public bool? SpecialFlag { get; set; }
        public bool? LockFlag { get; set; }
        public string Unit4rentPrice { get; set; }
        public string Unit4rentunitPrice { get; set; }
        public DateTime? LastUpdateDate { get; set; }
        public DateTime? LastFollowupDate { get; set; }
        public DateTime? LastRealtyStatusDate { get; set; }
        public DateTime? LastPriceDate { get; set; }
        public bool? ImageFlag { get; set; }
        public int? TradeType { get; set; }
        public int? RealtyStatus { get; set; }
        public DateTime? DeliveryDate { get; set; }
        public DateTime? RentEndDate { get; set; }
        public DateTime? OriginalRegisterDate { get; set; }
        public DateTime? RentCommissionDate { get; set; }
        public DateTime? SaleCommissionDate { get; set; }
        public DateTime? FilingStartDate { get; set; }
        public DateTime? FilingEndDate { get; set; }
        public double? SalePrice { get; set; }
        public double? SaleUnitPrice { get; set; }
        public double? RentPrice { get; set; }
        public double? RentUnitPrice { get; set; }
        public double? BasePrice { get; set; }
        public double? TransferFee { get; set; }
        public double? ManagementFee { get; set; }
        public double? AirConditioningFee { get; set; }
        public double? ConstructionArea { get; set; }
        public double? UsageArea { get; set; }
        public double? TransmissionArea { get; set; }
        public int? PayType { get; set; }
        public int? ConstructionType { get; set; }
        public int? ShopType { get; set; }
        public int? OfficeType { get; set; }
        public int? CommissionType { get; set; }
        public string CommissionNum { get; set; }
        public string PropertyNum { get; set; }
        public int? ViewType { get; set; }
        public string KeyNum { get; set; }
        public string FilingNum { get; set; }
        public int? RegisterEmployeeId { get; set; }
        public string RegisterEmployeeName { get; set; }
        public int? RegisterDepartmentId { get; set; }
        public string RegisterDepartmentName { get; set; }
        public int? RentEmployeeId { get; set; }
        public string RentEmployeeName { get; set; }
        public int? RentDepartmentId { get; set; }
        public string RentDepartmentName { get; set; }
        public int? SaleEmployeeId { get; set; }
        public string SaleEmployeeName { get; set; }
        public int? SaleDepartmentId { get; set; }
        public string SaleDepartmentName { get; set; }
        public int? KeyEmployeeId { get; set; }
        public string KeyEmployeeName { get; set; }
        public int? KeyDepartmentId { get; set; }
        public string KeyDepartmentName { get; set; }
        public int? SoleAgentEmployeeId { get; set; }
        public string SoleAgentEmployeeName { get; set; }
        public int? SoleAgentDepartmentId { get; set; }
        public string SoleAgentDepartmentName { get; set; }
        public int? FilingEmployeeId { get; set; }
        public string FilingEmployeeName { get; set; }
        public int? FilingDepartmentId { get; set; }
        public string FilingDepartmentName { get; set; }
        public int? OwnerEmployeeId { get; set; }
        public int? DecorationLevel { get; set; }
        public int? RoomNum { get; set; }
        public int? LivingRoomNum { get; set; }
        public int? ToiletNum { get; set; }
        public int? BalconyNum { get; set; }
        public int? FaceOrientation { get; set; }
        public int? ShopLocation { get; set; }
        public string ShopTradeType { get; set; }
        public string ShopTradeName { get; set; }
        public double? RoomDepth { get; set; }
        public double? RoomWidth { get; set; }
        public double? RoomHeight { get; set; }
        public int? AirConditionerType { get; set; }
        public double? Returns { get; set; }
        public int? Toilet { get; set; }
        public int? OfficeClass { get; set; }
        public double? OvertimeAirConditioningFee { get; set; }
        public int? PhoneReadtimes { get; set; }
        public int? RealtyType { get; set; }
        public int? SeparatedNum { get; set; }
        public string Memo { get; set; }
        public int? UseType { get; set; }
        public bool? BambooFlag { get; set; }
        public double? BaseUnitPrice { get; set; }
        public string AirConditioningFeeUnit { get; set; }
        public double? TransmissionAreaChi { get; set; }
        public int? RealtyFloors { get; set; }
        public double? UsageRatio { get; set; }
        public string OvertimeAirConditioningFeeUnit { get; set; }
        public DateTime? OpeningDatetime { get; set; }
        public bool? DeleteFlag { get; set; }
        public bool? DictionaryFlag { get; set; }
        public DateTime? PhoneReadtimesDate { get; set; }
        public int? ManagementFeeUnit { get; set; }
        public DateTime? LockDatetime { get; set; }
        public int? CertificationYears { get; set; }
        public bool? RentAgencyFlag { get; set; }
        public int? RentQueryCode { get; set; }
        public int? SaleQueryCode { get; set; }
        public string Facilities { get; set; }
        public DateTime? CommissionDate { get; set; }
        public int? ExRentEmployeeId { get; set; }
        public int? ExRentDepartmentId { get; set; }
        public int? ExSaleEmployeeId { get; set; }
        public int? ExSaleDepartmentId { get; set; }
        public string ExRentEmployeeName { get; set; }
        public string ExRentDepartmentName { get; set; }
        public string ExSaleEmployeeName { get; set; }
        public string ExSaleDepartmentName { get; set; }
        public DateTime? CertificationDate { get; set; }
        public double? OriginalPrice { get; set; }
        public bool? FamilyUnique { get; set; }
        public bool? CommitmentFlag { get; set; }
        public DateTime? LastEncounterDate { get; set; }
        public int? RentPriceUpOrDown { get; set; }
        public int? SalePriceUpOrDown { get; set; }
        public int? InspectStatus { get; set; }
        public DateTime? LastInspectTime { get; set; }
        public DateTime? LimitCommissionDate { get; set; }
        public bool? HouseCheckFlag { get; set; }
        public bool? CertificateFlag { get; set; }
        public DateTime? LastSalesmanFollowupDate { get; set; }
        public DateTime? SpecialDatetime { get; set; }
        public int? DataFrom { get; set; }
        public int? PhoneInputEmployeeId { get; set; }
        public string PhoneInputEmployeeName { get; set; }
        public int? PhoneInputDepartmentId { get; set; }
        public string PhoneInputDepartmentName { get; set; }
        public int? SurveyEmployeeId { get; set; }
        public string SurveyEmployeeName { get; set; }
        public int? SurveyDepartmentId { get; set; }
        public string SurveyDepartmentName { get; set; }
        public int? RentDelegationEmployeeId { get; set; }
        public string RentDelegationEmployeeName { get; set; }
        public int? RentDelegationDepartmentId { get; set; }
        public string RentDelegationDepartmentName { get; set; }
        public int? SaleDelegationEmployeeId { get; set; }
        public string SaleDelegationEmployeeName { get; set; }
        public int? SaleDelegationDepartmentId { get; set; }
        public string SaleDelegationDepartmentName { get; set; }
        public bool? AreaCreated { get; set; }
    }
}
